--liquibase formatted sql
--liquibase update

--changeset Balaji Ramalingam:Alter-Table-Multi-Anchor-flow

ALTER TABLE LOT_STG_TP_SETUP_DTL MODIFY COLUMN LSTSD_TPSDID INT AUTO_INCREMENT;
ALTER TABLE LOT_STG_TP_INTEREST_DTL MODIFY COLUMN LSTCD_TPID INT AUTO_INCREMENT;
ALTER TABLE LOT_STG_TP_SETUP_DTL ADD CIF_ID int(11);

ALTER TABLE cp_proposed_products ADD COLUMN vintage_with_anchor bigint(20) DEFAULT NULL, ADD COLUMN min_monthly_anchor bigint(20) DEFAULT NULL, ADD COLUMN anchor_relationship VARCHAR(5) DEFAULT NULL;

INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5332,'KYC','2023-08-31 17:24:38.313000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5334,'KYC','2023-08-31 17:26:11.012000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5335,'KYC','2023-08-31 17:28:30.319000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5336,'KYC','2023-08-31 17:31:23.449000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5337,'KYC','2023-08-31 18:56:18.859000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5338,'KYC','2023-08-31 18:57:50.628000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5339,'KYC','2023-08-31 18:58:42.272000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5340,'KYC','2023-08-31 18:59:21.983000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5341,'KYC','2023-08-31 18:59:56.193000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5342,'KYC','2023-08-31 19:00:26.770000','Balaji','Other Credit Documents',0,'otherCreditDocuments',10,1,NULL,'Balaji',15591,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5343,'KYC','2023-08-31 19:07:10.162000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5344,'KYC','2023-08-31 19:10:08.902000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5345,'KYC','2023-08-31 19:10:27.776000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5346,'KYC','2023-08-31 19:11:04.786000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5347,'KYC','2023-08-31 19:11:49.328000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5348,'KYC','2023-08-31 19:11:58.119000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5349,'KYC','2023-08-31 19:12:19.024000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5350,'KYC','2023-08-31 19:12:33.345000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5351,'KYC','2023-08-31 19:12:40.296000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5352,'KYC','2023-08-31 19:13:22.282000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5353,'KYC','2023-08-31 19:15:41.057000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5354,'KYC','2023-08-31 19:16:12.302000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15593,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5355,'KYC','2023-08-31 19:18:14.637000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5356,'KYC','2023-08-31 19:18:22.590000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5357,'KYC','2023-08-31 19:18:30.646000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5358,'KYC','2023-08-31 19:18:36.693000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5359,'KYC','2023-08-31 19:18:55.826000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5360,'KYC','2023-08-31 19:19:02.666000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5361,'KYC','2023-08-31 19:19:13.625000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5362,'KYC','2023-08-31 19:19:30.599000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5363,'KYC','2023-08-31 19:19:38.293000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5364,'KYC','2023-08-31 19:19:44.778000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5365,'KYC','2023-08-31 19:19:56.174000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5366,'KYC','2023-08-31 19:20:01.741000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15595,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5368,'KYC','2023-08-31 19:23:01.878000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5369,'KYC','2023-08-31 19:23:36.379000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5370,'KYC','2023-08-31 19:23:42.438000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5371,'KYC','2023-08-31 19:23:48.254000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5372,'KYC','2023-08-31 19:24:06.455000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5373,'KYC','2023-08-31 19:24:14.242000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5374,'KYC','2023-08-31 19:24:28.186000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5375,'KYC','2023-08-31 19:24:40.973000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5376,'KYC','2023-08-31 19:24:50.301000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5377,'KYC','2023-08-31 19:24:56.242000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5378,'KYC','2023-08-31 19:25:05.931000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5379,'KYC','2023-08-31 19:25:12.000000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15597,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5380,'KYC','2023-08-31 19:26:40.573000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5381,'KYC','2023-08-31 19:26:46.016000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5382,'KYC','2023-08-31 19:26:51.749000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5383,'KYC','2023-08-31 19:26:59.273000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5384,'KYC','2023-08-31 19:27:04.051000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5385,'KYC','2023-08-31 19:27:10.500000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5386,'KYC','2023-08-31 19:27:16.121000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5387,'KYC','2023-08-31 19:27:23.055000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5388,'KYC','2023-08-31 19:27:30.671000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5389,'KYC','2023-08-31 19:27:35.432000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5390,'KYC','2023-08-31 19:27:41.314000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5391,'KYC','2023-08-31 19:27:47.690000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15599,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5392,'KYC','2023-09-01 10:34:16.882000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5393,'KYC','2023-09-01 10:34:22.075000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5394,'KYC','2023-09-01 10:34:27.499000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5395,'KYC','2023-09-01 10:34:38.108000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5396,'KYC','2023-09-01 10:34:44.484000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5397,'KYC','2023-09-01 10:34:50.841000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5398,'KYC','2023-09-01 10:35:07.504000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5399,'KYC','2023-09-01 10:35:18.903000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5400,'KYC','2023-09-01 10:35:25.044000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5401,'KYC','2023-09-01 10:35:32.453000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5402,'KYC','2023-09-01 10:35:43.684000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5403,'KYC','2023-09-01 10:35:53.418000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15601,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5404,'KYC','2023-09-01 10:40:18.148000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5405,'KYC','2023-09-01 10:40:31.182000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5406,'KYC','2023-09-01 10:40:37.594000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5407,'KYC','2023-09-01 10:40:42.271000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5408,'KYC','2023-09-01 10:40:49.061000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5409,'KYC','2023-09-01 10:40:55.008000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5410,'KYC','2023-09-01 10:41:04.426000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5411,'KYC','2023-09-01 10:41:14.123000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5412,'KYC','2023-09-01 10:41:24.983000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5413,'KYC','2023-09-01 10:43:58.714000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5414,'KYC','2023-09-01 10:44:05.648000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5415,'KYC','2023-09-01 10:44:09.302000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15603,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5416,'KYC','2023-09-23 21:51:53.848000','Balaji','Audited Financials',0,'auditedFinancials',1,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5417,'KYC','2023-09-23 21:52:29.110000','Balaji','GST Returns',0,'gstReturns',2,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5418,'KYC','2023-09-23 21:52:56.273000','Balaji','Anchor Ledger',0,'anchorLedger',3,1,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5419,'KYC','2023-09-23 21:53:21.295000','Balaji','Bank Statements',0,'bankStatements',4,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5420,'KYC','2023-09-23 21:54:06.796000','Balaji','Sanction Letter of Main CC/OD',0,'sanctionLetterOfMainCCOD',5,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5421,'KYC','2023-09-23 21:54:28.543000','Balaji','Sanction Letter of Bill Discounting Facility',0,'sanctionLetterOfBillDiscountingFacility',6,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5422,'KYC','2023-09-23 21:55:11.899000','Balaji','Anchor Recomm. Letter',1,'anchorRecommLetter',7,1,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5423,'KYC','2023-09-23 22:03:44.127000','Balaji','Business MIS',0,'businessMIS',8,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5424,'KYC','2023-09-23 22:04:07.620000','Balaji','Management Certified Provisional Financial Statements',0,'managementCertifiedProvisionalFinancialStatements',9,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5425,'KYC','2023-09-23 22:04:54.458000','Balaji','Latest Audited Financials(Group Company, If CG is Availed)',0,'latestAuditedFinancials',10,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5426,'KYC','2023-09-23 22:05:16.590000','Balaji','Related Party Transactions: Sale, Purchase etc',0,'relatedPartyTransactionsSale_Purchase',11,0,NULL,'Balaji',15605,'v1',0,0,0);
INSERT INTO dms_document_list (`id`,`category`,`created_at`,`created_by`,`display_name`,`mandatory`,`name`,`seq_no`,`status`,`updated_at`,`updated_by`,`doc_category_id`,`version`,`deferral`,`type`,`deferral_time`) VALUES (5427,'KYC','2023-09-23 22:05:44.085000','Balaji','Other Credit Documents',0,'otherCreditDocuments',12,1,NULL,'Balaji',15605,'v1',0,0,0);

UPDATE soft_policy_master_sub_type SET regex = '^[0-9]{1,10}(\\.[0-9]{0,2})?$' WHERE (`id` = '153');
UPDATE soft_policy_master_sub_type SET regex = '^[0-9]{1,10}(\\.[0-9]{0,2})?$' WHERE (`id` = '158');
UPDATE soft_policy_master_sub_type SET regex = '^[0-9]{1,10}(\\.[0-9]{0,2})?$' WHERE (`id` = '159');

ALTER TABLE cp_limit_eligibility_details ADD COLUMN receivables double DEFAULT NULL, ADD COLUMN inventory double DEFAULT NULL, ADD COLUMN creditor double DEFAULT NULL, ADD COLUMN expected_monthly_turnover_with_anchor double NOT NULL, ADD COLUMN model_adhoc_limit double NOT NULL;

ALTER TABLE cp_limit_eligibility_details MODIFY COLUMN door_to_door varchar(255) DEFAULT NULL;
ALTER TABLE cp_limit_eligibility_details MODIFY COLUMN invoice_ageing varchar(255) DEFAULT NULL;

INSERT INTO credit_policy_master (id, created_at, data_type, display_name, mandatory, policy_name, policy_type, regex, status) VALUES ('28', '2023-09-04 11:54:00', 'CheckPolicy', 'Total Inward Cheques', '1', 'TotalInwardCheques', 'Credit Policy', '^[0-9]{1,4}$', '1');

UPDATE credit_policy_master SET status = '0' WHERE (id = '26');
UPDATE credit_policy_master SET status = '0' WHERE (id = '27');

UPDATE credit_policy_master SET mandatory = '0' WHERE (id = '26');
UPDATE credit_policy_master SET mandatory = '0' WHERE (id = '27');

INSERT INTO credit_policy_filters (id, formula, type, config_id, display_name_id) VALUES ('325', 'Validate', '1', '1', '28'),('326', 'Validate', '1', '2', '28'), ('327', 'Validate', '0', '3', '28'), ('328', 'Validate', '1', '4', '28'), ('329', 'Validate', '1', '5', '28'), ('330', 'Validate', '0', '6', '28'), ('331', 'Validate', '1', '7', '28'), ('332', 'Validate', '1', '8', '28'), ('333', 'Validate', '1', '9', '28'), ('334', 'Validate', '1', '10', '28'),('335', 'Validate', '1', '11', '28'), ('336', 'Validate', '1', '12', '28');

ALTER TABLE cp_limit_eligibility_details MODIFY column margin double default null ;
ALTER TABLE cp_limit_eligibility_details MODIFY column calculated_limit_wo_set_off double default null ;

UPDATE credit_norms_master SET display_name = 'Monthly Purchase from Anchor', name = 'MonthlyPurchasefromAnchor' WHERE (id = '266');
UPDATE credit_policy_master SET display_name = 'Min Vintage with Anchor (in Months)' WHERE (id = '26');

ALTER TABLE anchor_beneficiary MODIFY COLUMN bank_acct_number VARCHAR(25) DEFAULT NULL;