/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.vcpl.triton;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class TritonApplicationTest {
    @Test
    public void testGetMessage() {
        assertEquals("I am triton application", TritonApplication.getMessage());
    }
}
