*** Settings ***
Resource    ../../keywords/variables.robot
Test Template       TC_CP_commercial_cc_datafile_id
Suite Setup            Business_Authentication
*** Keywords ***
 Business_Authentication
    ${username}    Set Variable       business_lead
    ${password}    Set Variable       admin@1234
    Obtain_Auth_Token    ${username}    ${password}

*** Test Cases ***                             ${adhocLimitRemarks}        ${anchorNameRemarks}       ${appId}            ${creditPeriodRemarks}       ${doorRemarks}      ${interestRateRemarks}        ${interestTypeRemarks}      ${invoiceAgeingRemarks}        ${marginRemarks}      ${pfRemarks}          ${productRemarks}         ${regularLimitRemarks}        ${renewalPeriodRemarks}     ${renewalRemarks}   
# TC_CPCC_00_missing_appid                         adhoclimit                  anchorname               ${EMPTY}                  creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_02_missing_adhocLimitRemarks             ${EMPTY}                    anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_03_missing_productRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks                ${EMPTY}                regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_04_missing_anchorNameRemarks             adhoclimit                  ${EMPTY}                 ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_05_missing_regularLimitRemarks           adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks             ${EMPTY}                    renewalPeriod              renewal
TC_CPCC_06_missing_creditPeriodRemarks           adhoclimit                  anchorname               ${cp_app_id}              ${EMPTY}                  door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_07_missing_doorRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_08_missing_InvoiceAgeingRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              ${EMPTY}          interestRate                   interestType                  ${EMPTY}                       margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_09_missing_marginRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  ${EMPTY}            pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_10_missing_intRateRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              ${EMPTY}                       interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_11_missing_pfRemarks                     adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              ${EMPTY}               productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_12_missing_renewalRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              ${EMPTY} 
TC_CPCC_14_missing_RenewalPeriodRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renawal
TC_CPCC_13_missing_intTypeRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   ${EMPTY}                      invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          ${EMPTY}                   renewal  
TC_CPCC_15_CAPS_anchornameRemarks                ADHOCLIMIT                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_16_CAPS_productRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              PRODUCTREMARKS            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_17_CAPS_anchorNameRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_18_CAPS_regularLimitRemarks              adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            REGULARLIMITREMARKS          renewalPeriod              renewal
TC_CPCC_19_CAPS_creditPeriodRemarks              adhoclimit                  anchorname               ${cp_app_id}              CREDITPERIOD              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_20_CAPS_doorRemarks                      adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_21_CAPS_InvoiceAgeingRemarks             adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  INVOICEAGEING                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_22_CAPS_marginRemarks                    adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  MARGIN              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_23_CAPS_intRateRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              INTERESTRATE                   interestType                  invoiceAgeing                  margin              pfremarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_24_CAPS_pfRemarks                        adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              OFREMARKS              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_25_CAPS_renewalRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              RENEWAL
TC_CPCC_26_CAPS_intTypeRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   INTERESTTYPE                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_27_CAPS_RenewalPeriodRemarks             adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          RENEWALPERIOD              renewal
TC_CPCC_29_numbers_anchornameRemarks             8912871293                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_30_numbers_productRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              87654321                  regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_31_numbers_anchorNameRemarks             adhoclimit                  8912831293               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_32_numbers_regularLimitRemarks           adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks             87654321                    renewalPeriod              renewal
TC_CPCC_33_numbers_creditPeriodRemarks           adhoclimit                  anchorname               ${cp_app_id}              81239182312               door              87654321                       interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_34_numbers_doorRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod              87654321          interestRate                   87654321                      invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_35_numbers_InvoiceAgeingRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  87654321                       margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_36_numbers_marginRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  87654321            pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_37_numbers_intRateRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interstrate                    interestType                  invoiceAgeing                  margin              pfremarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_38_numbers_pfRemarks                     adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              87654321               productReamrks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_39_numbers_renewalRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              87654321
TC_CPCC_40_numbers_intTypeRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   87654321                      invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_41_numbers_RenewalPeriodRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks           87654321                  renewal
TC_CPCC_43_spcChar_anchornameRemarks             !@#$%^&*@@                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_44_spcChar_productRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              $%^&&*":                  regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_45_spcChar_anchorNameRemarks             adhoclimit                  *&%^&$*^$*               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_46_spcChar_regularLimitRemarks           adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            $%^&&*":                     renewalPeriod              renewal
TC_CPCC_47_spcChar_creditPeriodRemarks           adhoclimit                  anchorname               ${cp_app_id}              $%^&&*":                  door              interestrate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_48_spcChar_doorRemarks                   adhoclimit                  anchorname               ${cp_app_id}              creditperiod             $%^&&*":           interestRate                   $%^&&*":                      invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_49_spcChar_InvoiceAgeingRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  $%^&&*":                       margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_50_spcChar_marginRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  $%^&&*":            pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_51_spcChar_intRateRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door                 $%^&&*":                    interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_52_spcChar_pfRemarks                     adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              $%^&&*":               productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_53_spcChar_renewalRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              $%^&&*":
TC_CPCC_54_spcChar_intTypeRemarks                adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   $%^&&*":                      invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_55_spcChar_RenewalPeriodRemarks          adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          $%^&&*":                   renewal
TC_CPCC_57_spaces_anchornameRemarks              abc abc                      abc abc                 ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_58_spaces_productRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks                abc abc                 regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_59_spaces_anchorNameRemarks              adhoclimit                  abc abc                  ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_60_spaces_regularLimitRemarks            adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks               abc abc                   renewalPeriod              renewal
TC_CPCC_61_spaces_creditPeriodRemarks            adhoclimit                  anchorname               ${cp_app_id}              abc abc                   door              interestrate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_62_spaces_doorRemarks                    adhoclimit                  anchorname               ${cp_app_id}              creditperiod              abc abc           interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_63_spaces_InvoiceAgeingRemarks           adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  abc abc                        margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_64_spaces_marginRemarks                  adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  abc abc             pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_65_spaces_intRateRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door                abc abc                      interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_66_spaces_pfRemarks                      adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              abc abc                productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_67_spaces_renewalRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              abc abc
TC_CPCC_68_spaces_intTypeRemarks                 adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   abc abc                       invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          renewalPeriod              renewal
TC_CPCC_69_spaces_RenewalPeriodRemarks           adhoclimit                  anchorname               ${cp_app_id}              creditperiod              door              interestRate                   interestType                  invoiceAgeing                  margin              pfRemarks              productRemarks            regularLimitRemarks          abc abc                    renewal




